# elaticsearch role

- name: Install apt key for elasticsearch repository
  apt_key:
    url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch
    state=present

- name: Install apt elasticsearch repository
  apt_repository:
    repo='deb http://packages.elasticsearch.org/elasticsearch/{{elasticsearch.version}}/debian stable main'
    state=present

- name: Install curl
  apt:
    name=curl
    state=present

- name: Install Elasticsearch
  apt:
    name=elasticsearch
    state=latest
    force=yes
  tags: elasticsearch
  notify: Start Elasticsearch on boot

# Install Elasticsearch plugins
- include: plugins.yml

- name: Configure Elasticsearch
  template:
    src=elasticsearch.conf.j2
    dest=/etc/elasticsearch/elasticsearch.yml
    owner=root
    group=root
    mode=0644
  notify: Restart Elasticsearch

- service: name=elasticsearch state=started